woowacourse-teams/2025-pick-eat

frontend/.eslintrc.json
frontend/package-lock.json
frontend/package.json
frontend/src/main.tsx
frontend/src/routes/routePath.ts
frontend/src/routes/router.tsx
frontend/tsconfig.json
frontend/webpack.common.js

Feature/11 라우터 설정

---

backend/src/main/java/com/pickeat/backend/room/application/RoomService.java
backend/src/main/java/com/pickeat/backend/room/domain/Room.java
backend/src/main/java/com/pickeat/backend/room/domain/repository/RoomRepository.java
backend/src/main/java/com/pickeat/backend/room/ui/RoomController.java

#27 
- 방 정보 조회 기능 구현
- 방 정보 조회 API 구현
- 방 생성 HttpState 값 변경

[Feat] 방 정보 조회 기능 구현

---

frontend/.storybook/main.ts
frontend/.storybook/preview.tsx
frontend/package-lock.json
frontend/package.json
frontend/src/shared/components/actions/Input.stories.tsx
frontend/src/shared/components/actions/Input.tsx

#19 
Input 컴포넌트 구현
- Input 컴포넌트 구현
- Storybook 작성

[Feat] 인풋 컴포넌트 구현

---

frontend/.storybook/main.ts
frontend/.storybook/preview.tsx
frontend/package-lock.json
frontend/package.json
frontend/public/images/arrow.svg
frontend/src/shared/components/actions/Input.stories.tsx
frontend/src/shared/components/actions/Input.tsx
frontend/src/shared/components/actions/Select.stories.tsx
frontend/src/shared/components/actions/Select.tsx
frontend/src/shared/components/assets/icons/Arrow.tsx
frontend/src/shared/hooks/useBoolean.ts

#15 
셀렉트 컴포넌트 구현
- 셀렉트 컴포넌트
- Storybook 작성
Input 컴포넌트 만들면서 잘못 rebase해서 Input이랑 겹쳤네용...
죄둉합니다..

[Feat] 셀렉트 컴포넌트 구현

---

frontend/package-lock.json
frontend/package.json
frontend/src/apis/apiClient.ts
frontend/src/domains/errorBoundary/ErrorBoundary.tsx
frontend/src/shared/components/actions/Button.stories.tsx
frontend/src/shared/components/actions/Button.tsx
frontend/webpack.common.js

Feature/36 페이지 구현

---

frontend/babel.config.json
frontend/package-lock.json
frontend/package.json
frontend/src/apis/apiClient.ts
frontend/src/domains/errorBoundary/ErrorBoundary.tsx
frontend/src/domains/matchResult/hooks/useResult.ts
frontend/src/pages/MatchResult.tsx
frontend/src/routes/routePath.ts
frontend/src/routes/router.tsx
frontend/src/shared/components/Confetti.tsx
frontend/src/shared/components/actions/Button.stories.tsx
frontend/src/shared/components/actions/Button.tsx
frontend/webpack.common.js
package-lock.json

[Feat] 결과 페이지 구현

---

.github/workflows/fe-ci.yml

[CI] 프론트 CI 구축

---

.github/workflows/ci-check.yml
.github/workflows/cicd.yml
backend/Dockerfile
backend/docker/docker-compose.dev.yml
backend/src/main/java/com/pickeat/backend/room/ui/RoomController.java

[Cicd] 백엔드 cicd 구축

---

frontend/src/domains/matchResult/hooks/useResult.ts
frontend/src/domains/preferRestaurant/components/PreferRestaurantItem.tsx
frontend/src/domains/preferRestaurant/components/PreferRestaurantList.tsx
frontend/src/domains/preferRestaurant/context/PreferRestaurantProvider.tsx
frontend/src/domains/preferRestaurant/hooks/useParticipant.ts
frontend/src/domains/restaurantExclude/components/actions/ExcludeSubmitButton.tsx
frontend/src/pages/MatchResult.tsx
frontend/src/pages/PreferRestaurant.tsx
frontend/src/pages/RoomDetail.tsx

[Refactor] 선호 식당 페이지 리팩터링

---

frontend/src/domains/restaurantExclude/components/RestaurantExclude.tsx
frontend/src/domains/restaurantExclude/components/restaurantTabList/RestaurantTabList.tsx
frontend/src/domains/restaurantExclude/components/restaurantTabList/hooks/useRestaurantsData.ts
frontend/src/domains/restaurantExclude/components/restaurantTabList/hooks/useRestaurantsPolling.ts
frontend/src/shared/components/tabMenus/TabContent.tsx
frontend/src/shared/hooks/usePolling.ts

#118 
공용 폴링 훅을 구현하였습니다!
확인 부탁드립니다~

[Refactor] 코드 리팩토링

---

backend/src/main/java/com/pickeat/backend/global/exception/ErrorCode.java
backend/src/main/java/com/pickeat/backend/restaurant/application/WishRestaurantSearchService.java
backend/src/main/java/com/pickeat/backend/wish/application/WishListService.java
backend/src/main/java/com/pickeat/backend/wish/application/WishService.java
backend/src/main/java/com/pickeat/backend/wish/ui/WishController.java
backend/src/main/java/com/pickeat/backend/wish/ui/WishListController.java
backend/src/main/java/com/pickeat/backend/wish/ui/api/WishApiSpec.java
backend/src/main/java/com/pickeat/backend/wish/ui/api/WishListApiSpec.java
backend/src/test/java/com/pickeat/backend/wish/application/WishListServiceTest.java
backend/src/test/java/com/pickeat/backend/wish/application/WishServiceTest.java

#148 
- 비회원의 공용 위시리스트 조회
- 비회원의 공용 위시리스트의 위시 조회
#148

[Feat] 비회원 위시리스트와 위시 조회기능 구현

---

backend/src/main/java/com/pickeat/backend/global/exception/ErrorCode.java
backend/src/main/java/com/pickeat/backend/pickeat/application/PickeatService.java
backend/src/main/java/com/pickeat/backend/pickeat/ui/PickeatController.java
backend/src/main/java/com/pickeat/backend/pickeat/ui/api/PickeatApiSpec.java
backend/src/main/java/com/pickeat/backend/restaurant/domain/Restaurants.java
backend/src/test/java/com/pickeat/backend/fixture/RestaurantFixture.java
backend/src/test/java/com/pickeat/backend/pickeat/application/PickeatServiceTest.java
backend/src/test/java/com/pickeat/backend/restaurant/domain/RestaurantsTest.java

[Feat] 픽잇 결과 단건 조회 기능 추가

---

backend/src/main/java/com/pickeat/backend/global/init/DataInitializer.java

#157 
초기 방과 초기 위시리스트를 생성하는 세팅 추가
#157

feat: 초기 위시리스트 데이터 삽입 세팅

---

backend/src/main/java/com/pickeat/backend/wish/application/WishListService.java
backend/src/main/java/com/pickeat/backend/wish/ui/WishListController.java
backend/src/main/java/com/pickeat/backend/wish/ui/api/WishListApiSpec.java
backend/src/test/java/com/pickeat/backend/wish/application/WishListServiceTest.java

#185 
위시리스트 삭제 API 구현
close #185

feat: 위시리스트 삭제 API 구현

---

backend/src/main/java/com/pickeat/backend/pickeat/application/PickeatService.java
backend/src/main/java/com/pickeat/backend/pickeat/application/dto/response/PickeatResponse.java
backend/src/main/java/com/pickeat/backend/pickeat/domain/repository/PickeatRepository.java
backend/src/main/java/com/pickeat/backend/pickeat/ui/PickeatController.java
backend/src/main/java/com/pickeat/backend/pickeat/ui/api/PickeatApiSpec.java
backend/src/test/java/com/pickeat/backend/pickeat/application/PickeatServiceTest.java

#188 
방에서 활성화된 픽잇 리스트를 조회하는 API를 구현
close #188

feat: 방의 활성화된 픽잇 조회 API 구현

---

backend/src/main/java/com/pickeat/backend/wish/application/WishListService.java
backend/src/main/java/com/pickeat/backend/wish/ui/WishListController.java
backend/src/main/java/com/pickeat/backend/wish/ui/api/WishListApiSpec.java
backend/src/test/java/com/pickeat/backend/wish/application/WishListServiceTest.java

#197 
- 방의 위시리스트를 조회할 떄는 공용 위시리스트는 조회되지 않도록 수정
close #197

[Refactor] 방의 위시리스트 조회 기능 개선

---

backend/src/main/java/com/pickeat/backend/global/exception/GlobalExceptionHandler.java
backend/src/main/java/com/pickeat/backend/wish/application/WishListService.java
backend/src/main/java/com/pickeat/backend/wish/application/WishService.java
backend/src/main/java/com/pickeat/backend/wish/application/dto/request/WishUpdateRequest.java
backend/src/main/java/com/pickeat/backend/wish/domain/Wish.java
backend/src/main/java/com/pickeat/backend/wish/ui/WishController.java
backend/src/main/java/com/pickeat/backend/wish/ui/api/WishApiSpec.java
backend/src/test/java/com/pickeat/backend/wish/application/WishListServiceTest.java
backend/src/test/java/com/pickeat/backend/wish/application/WishPictureServiceTest.java
backend/src/test/java/com/pickeat/backend/wish/application/WishServiceTest.java
backend/src/test/java/com/pickeat/backend/wish/domain/WishTest.java

#194 
- 위시 수정 API 구현
- 위시 도메인 관련 테스트 정리
- 잘못된 요청에 대한 핸들링 추가
- 잘못된 HTTP 메서드와  URL에 대한 예외 핸들링
- 잘못된 컨텐츠 타입에 대한 예외 핸들링
- 파일업로드시 잘못된 요청 형식과 너무 큰 파일 크기에 대한 예외 핸들링
close #194

[Feat] 위시 수정 api 구현

---

backend/src/main/java/com/pickeat/backend/wish/application/WishPictureService.java
backend/src/main/java/com/pickeat/backend/wish/ui/WishPictureController.java
backend/src/main/java/com/pickeat/backend/wish/ui/api/WishPictureApiSpec.java
backend/src/test/java/com/pickeat/backend/wish/application/WishPictureServiceTest.java

#203 
- 위시 사진 삭제 API 구현
- 위시 사진 수정 API 구현
close #203

[Feat] 위시 사진 관련 api 추가 구현

---

frontend/src/domains/wishlist/components/Wishes.tsx
frontend/src/shared/components/progressBar/ProgressBar.stories.tsx
frontend/src/shared/components/progressBar/ProgressBar.tsx

#192 
- 디자인
처음에 보여드렸던 거보다 좀 많이 허술해진 것 같네요 다들 그라데이션 없애라고 해서 눈물을 머금고 없앴습니다힝,,
마지막에 결과가 완성되면 치즈로 콕 찌르는 gif나 이미지가 들어가면 귀여울 것 같은데 어떤가요?!
디자인 추피드백 환영이용 처음 구현한 게 정말 내 취향이었는데 아무도 안예쁘다해서 슬프네,,,,,
기죽어서 젤 기본으루 다시 만듦 치즈는 그래두 포기 못한다.(옵션입니다)
- 사용 방식
위이잉 움직이는 구간 설정하실 때 스토리북에 작성된 코드 참고해서 쓰시면 되는데 복잡하면 내부에서 처리하는 방식으로 바꿔볼게요! 저는 현재 구조가 여러 상황(움직임x/구간 움직임/움직일 타이밍 지정 등)에 대처하기 적합하다고 생각했습니다!
- 구간 및 라벨 제거
저번에 보여드린 구간과 라벨은 피드백을 받고 전부 제거했습니다.(프로그레스 바는 진척도만 보여줘도 충분하다 & 모바일에서 라벨이 다닥다닥 붙어있어 안예쁘다 등) 옵션으로 넣을까 했는데 제거 버전이 코드가 너무 깔끔해서 없앴습니다. 필요성을 느끼신다면 다시 구현해 볼게요,,!

[Feature] 프로그레스 바 컴포넌트 구현

---

frontend/src/domains/matchResult/components/PickeatDecisionInfo.tsx
frontend/src/domains/matchResult/components/PickeatEndConfirm.tsx
frontend/src/domains/pickeat/components/ChoosePickeatType.tsx
frontend/src/domains/pickeat/utils/makePickeatName.ts
frontend/src/domains/preferRestaurant/components/PreferRestaurantItem.tsx
frontend/src/domains/room/components/ChooseRoomWishlist.tsx
frontend/src/domains/wishlist/components/PublicWishlist.tsx
frontend/src/domains/wishlist/components/WishlistCard.tsx
frontend/src/pages/Main.tsx
frontend/src/shared/components/Carousel.tsx
frontend/src/shared/components/actions/LikeButton/LikeButton.tsx

[Fix] 픽잇 긴급 초비상 버그 수정

---

backend/src/main/java/com/pickeat/backend/global/config/WebConfig.java
backend/src/main/java/com/pickeat/backend/global/exception/ErrorCode.java
backend/src/main/java/com/pickeat/backend/login/application/LoginClient.java
backend/src/main/java/com/pickeat/backend/login/application/LoginService.java
backend/src/main/java/com/pickeat/backend/login/application/dto/request/AuthCodeRequest.java
backend/src/main/java/com/pickeat/backend/login/infrastructure/KakaoLoginApiProperties.java
backend/src/main/java/com/pickeat/backend/login/infrastructure/KakaoLoginClient.java
backend/src/main/java/com/pickeat/backend/login/infrastructure/KakaoLoginConfig.java
backend/src/main/java/com/pickeat/backend/login/ui/api/LoginApiSpec.java

#219 
카카오 로그인 리다이렉트 주소 요청 형식 변경
카카오 로그인 리다이렉트 주소 요청 형식 변경
close #219

[Refactor] 카카오 로그인 리다이렉트 주소 요청 형식 변경

---

backend/src/main/java/com/pickeat/backend/pickeat/application/PickeatService.java
backend/src/main/java/com/pickeat/backend/pickeat/domain/repository/PickeatRepository.java
backend/src/main/java/com/pickeat/backend/pickeat/ui/PickeatController.java
backend/src/main/java/com/pickeat/backend/pickeat/ui/api/PickeatApiSpec.java
backend/src/test/java/com/pickeat/backend/pickeat/application/PickeatServiceTest.java

#236 
마이페이지에 추가할 진행중인 픽잇 조회  API 구현
#236

[Feat] 진행중인 픽잇 조회 API 구현

---

backend/src/main/java/com/pickeat/backend/wish/application/WishListService.java
backend/src/main/java/com/pickeat/backend/wish/application/WishService.java
backend/src/main/java/com/pickeat/backend/wish/application/dto/response/WishListResponse.java
backend/src/main/java/com/pickeat/backend/wish/domain/WishList.java
backend/src/main/java/com/pickeat/backend/wish/domain/repository/WishListRepository.java
backend/src/main/java/com/pickeat/backend/wish/ui/WishListController.java
backend/src/main/java/com/pickeat/backend/wish/ui/api/WishListApiSpec.java
backend/src/test/java/com/pickeat/backend/wish/application/WishListServiceTest.java

[Refactor] 위시리스트 객체 구조 변경

---

backend/docker/docker-compose.dev.yml

[Env] docker-compose-dev.yml 변경

---

backend/src/main/java/com/pickeat/backend/BackendApplication.java

#274 
개발 서버 접속 방식이 변경되어 swagger api 스펙의 변경이 필요했습니다.
swagger api 스펙에서 dev.api.pickeat -> IP 주소 로 변경되었습니다.

[Env] 개발 서버 swagger api 스펙 변경 변경

---

frontend/src/domains/pickeat/components/ChoosePickeatType.tsx
frontend/src/domains/profile/components/RoomList.tsx
frontend/src/domains/room/components/ChooseRoomWishlist.tsx

#293 
Modal content 내부에서 useEffect 사용하는 방식으로 변경했습니다!
tanstack query 도입을 고려해서 간단하게 처리만 해뒀습니당

[Fix] 메인 페이지에서 방 정보 요청 오류 해결

---

frontend/src/domains/pickeat/matchResult/components/Result.tsx
frontend/src/domains/profile/components/RoomList.tsx
frontend/src/domains/room/components/RoomDetailTab/RoomDetailName.tsx
frontend/src/pages/pickeat/matchResult/MatchResult.tsx
frontend/src/routes/router.tsx
frontend/src/shared/components/assets/LoadingSpinner.tsx

- 결과 페이지 버튼 깨짐 수정
- Spinner style 코드 위치 변경
- 방 목록 min-width 설정
- 방 이름 Pretendard체로 변경

[Hotfix] UI 깨지는 것 수정

---

frontend/src/domains/pickeat/matchResult/components/Result.tsx
frontend/src/domains/pickeat/participants/participantsAvatarGroup/ParticipantsAvatarGroup.tsx
frontend/src/domains/room/components/RoomDetailTab/index.tsx
frontend/src/domains/room/components/WishlistTab/WishlistTab.tsx
frontend/src/pages/pickeat/hooks/useReEntry.ts
frontend/src/pages/pickeat/matchResult/MatchResult.tsx
frontend/src/pages/pickeat/preferRestaurant/components/Title.tsx
frontend/src/pages/pickeat/restaurantExclude/components/Title.tsx
frontend/src/routes/router.tsx
frontend/src/shared/provider/ToastProvider.tsx

[Fix] 5차 데모 반영

---

backend/src/main/java/com/pickeat/backend/pickeat/application/PickeatResultService.java
backend/src/main/java/com/pickeat/backend/pickeat/ui/PickeatController.java
backend/src/main/java/com/pickeat/backend/pickeat/ui/api/PickeatApiSpec.java
backend/src/main/java/com/pickeat/backend/restaurant/application/RestaurantSearchFacade.java
backend/src/main/java/com/pickeat/backend/restaurant/application/WishRestaurantSearchService.java
backend/src/test/java/com/pickeat/backend/pickeat/application/PickeatResultServiceTest.java

#312
픽잇 결과 조회 시 불필요한 참가자 권한을 제거한다.

[Refactor]픽잇 결과 조회 권한 제거

---

backend/src/main/java/com/pickeat/backend/room/application/RoomService.java
backend/src/main/java/com/pickeat/backend/room/domain/repository/RoomUserRepository.java
backend/src/main/java/com/pickeat/backend/room/ui/RoomController.java
backend/src/main/java/com/pickeat/backend/room/ui/api/RoomApiSpec.java
backend/src/test/java/com/pickeat/backend/room/application/RoomServiceTest.java

#319 
방 나가기 기능이 필요해졌습니다.
방 나가기에 관한 api가 구현되었습니다.
현재 방에 마지막 남아있는 사람이 나갈 경우 방을 삭제하는 것이 좋아보입니다.
하지만 내일 진행될 도메인 변경사항 적용 후 구현하는 것이 좋아보여 추가하지 않았습니다.

[Feat] 방 나가기 기능 구현

---

backend/src/main/java/com/pickeat/backend/global/annotation/DeprecatedApi.java
backend/src/main/java/com/pickeat/backend/global/config/intercepter/DeprecationInterceptor.java
backend/src/main/java/com/pickeat/backend/restaurant/application/RestaurantService.java
backend/src/main/java/com/pickeat/backend/restaurant/application/WishRestaurantSearchService.java
backend/src/main/java/com/pickeat/backend/restaurant/application/dto/request/RestaurantRequest.java
backend/src/main/java/com/pickeat/backend/restaurant/domain/Restaurant.java
backend/src/main/java/com/pickeat/backend/template/domain/Template.java
backend/src/main/java/com/pickeat/backend/tobe/restaurant/application/RestaurantSearchFacade.java
backend/src/main/java/com/pickeat/backend/tobe/restaurant/application/RestaurantService.java
backend/src/main/java/com/pickeat/backend/tobe/restaurant/application/WishRestaurantSearchService.java
backend/src/main/java/com/pickeat/backend/tobe/restaurant/application/request/RestaurantRequest.java
backend/src/main/java/com/pickeat/backend/tobe/restaurant/application/request/WishRestaurantRequest.java
backend/src/main/java/com/pickeat/backend/tobe/restaurant/ui/RestaurantController.java
backend/src/main/java/com/pickeat/backend/tobe/restaurant/ui/api/RestaurantApiSpec.java
backend/src/main/resources/db/migration/V1__init.sql
backend/src/test/java/com/pickeat/backend/fixture/RestaurantFixture.java
backend/src/test/java/com/pickeat/backend/restaurant/application/RestaurantServiceTest.java

#328 
- DB 마이그레이션 스크립트 정합성 수정
- API 버저닝 인프라 구축 (V1/V2 병행 운영 준비)
- 이미지 관리 방식 개선
`pictureUrls` → `pictureKey` + `pictureUrl` 분리
- S3 키와 다운로드 URL 명확히 구분
- 관련 Service, Request, Test 수정

[Refactor]스키마 마이그레이션 및 template 도메인 추가

---

frontend/src/shared/components/actions/Select.tsx

#343 
https://github.com/user-attachments/assets/fe88eea3-d7e9-4c0d-a01f-ddb3753b269d
안녕하세요 머핀 카멜~~ 추잘?(추석 잘보내고 있냐는 뜻)
피그마 디자인에 맞춰 셀렉트 수정했습니당!!
후하 이제 반영만 하면 컴포넌트 끝이당 헤헤
즐추~

[Refactor] 셀렉트 리디자인
